version: '3.9'

services:
  app:
    build: .
    container_name: store
    depends_on:
      - postgres
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    restart: always
    env_file:
      - .env
    networks:
      - application

  postgres:
    image: postgres:latest
    container_name: pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - application

networks:
  application:
    driver: bridge